### ISSUE TITLE
Game won't launch on Windows, quantumQ_v1.0.pck is missing

### ISSUE THREAD

**Issue by OArndt** [ray-pH/quantumQ#2]
After launching the .exe-file I just get the following alert:

![image](https://user-images.githubusercontent.com/43098322/149862651-9afa9bb7-ab8e-4df2-87fc-2303002a8631.png)

It now works after following [this](https://www.reddit.com/r/Physics/comments/s653v9/comment/ht3ym61/) reddit comment and copying the quantumQ_v1.0.pck from the linux download into the same folder as the .exe.

**Comment by ray-pH** [comment]
Oh, yeah, i forgot to put the .pck file in the windows release.
Fixed it
