### ISSUE TITLE
Level 28 not letting me win. 

### ISSUE THREAD

**Issue by SirFlickka** [ray-pH/quantumQ#4]
I have tried a few seperate times and have screenshots of 
20 and 80%s at 00 and 01. 
I just found the source and found my first solution to solve
![Screenshot_20230122-100028](https://user-images.githubusercontent.com/114291178/213922794-44c78ea1-7a19-4625-bdbd-ff5958d0c776.png)

**Comment by ray-pH** [comment]
Oh, sorry, i think for this level the task and the given expected output is not clear enough. 
What i had in mind is to **swap** the top and the bottom qubit, that is just swapping the probability without altering the phase

You suppose to **swap** the coefficient of |01⟩ with |10⟩, while the coefficient for |00⟩ shouldn't be changed
i.e. the expected output is

0.4472 + 0i |00⟩
0.8944 + 0i |01⟩
0 + 0i |10⟩
0 + 0i |11⟩

**Comment by SirFlickka** [comment]
ok cool sorry.
i do like the app..
im working on alot..
